backend:
  name: git-gateway
  branch: main

media_folder: "media"
public_folder: "/media"

collections:
  - name: "products"
    label: "מוצרים"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "שם המוצר", name: "title", widget: "string" }
      - { label: "תיאור", name: "description", widget: "text", required: false }
      - { label: "מחיר", name: "price", widget: "number" }
      - { label: "קטגוריה", name: "category", widget: "select", options: ["דגים מעושנים", "זיתים"] }
      - { label: "תמונה", name: "image", widget: "image" }
