backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "menu"
    label: "תפריט"
    folder: "content/menu"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "שם המנה", name: "title", widget: "string"}
      - {label: "תיאור", name: "description", widget: "text"}
      - {label: "מחיר", name: "price", widget: "string"}
