backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "products"
    label: "מוצרים"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "שם", name: "title", widget: "string" }
      - { label: "מחיר", name: "price", widget: "string" }
      - { label: "תמונה", name: "image", widget: "image" }
      - { label: "קטגוריה", name: "category", widget: "select", options: ["דגים", "זיתים"] }
